publish_mode: editorial_workflow
backend:
    name: github
    repo: frain-dev/convoy
    branch: main
    squash_merges: true

media_folder: web/ui/website/static/blog/img
public_folder: /blog/img

media_library:
    name: cloudinary
    config:
        cloud_name: frain
        api_key: 149165965747484

site_url: https://getconvoy.netlify.app
show_preview_links: true

collections:
    - name: 'authors'
      label: 'Author'
      folder: 'web/ui/website/content/blog-authors'
      format: 'json'
      create: true
      slug: '{{name}}'
      fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'Twitter Handle', name: 'twitter', widget: 'string' }
          - { label: 'Github User Name', name: 'github', widget: 'string' }
          - { label: 'Role', name: 'role', widget: 'string' }

    - name: 'blog'
      label: 'Blog'
      folder: 'web/ui/website/content/blog'
      format: 'frontmatter'
      extension: 'markdown'
      preview_path: 'blog/{{slug}}'
      create: true
      slug: '{{slug}}'
      editor:
          preview: true
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }1
          - { label: 'Description', name: 'description', widget: 'string' }
          - label: 'Featured Image'
            name: 'featureImg'
            widget: 'image'
            media_library:
                config:
                    default_transformations:
                        - fetch_format: auto
                          width: 367
                          quality: auto
                          crop: 'scale'
          - label: 'Post Image'
            name: 'thumbnail'
            widget: 'image'
            media_library:
                config:
                    default_transformations:
                        - fetch_format: auto
                          width: 461
                          quality: auto
                          crop: 'scale'
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Tags', name: 'tags', widget: 'list', default: ['convoy'] }
					- {label: "Feature Post", name: "featurePost", widget: "boolean", default: false}
          - label: 'Post Author'
            name: 'author'
            widget: 'relation'
            collection: 'authors'
            search_fields: ['name', 'twitter', 'github']
            value_field: '{{slug}}'
            display_fields: ['{{name}}, {{role}}']
